dist: trusty

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk11

notifications:
  email:
      - notification@qos.ch

install: /bin/true

script:
  - mvn clean
  - mvn install
